server:
  port: 8081  # Puerto de ejecución del microservicio

spring:
  application:
    name: accounts-service  # Nombre de la app (aparece en logs y actuator)

  # Deshabilita verificación de compatibilidad Spring Cloud/Boot
  cloud:
    compatibility-verifier:
      enabled: false

  # === JPA / HIBERNATE ===
  jpa:
    hibernate:
      ddl-auto: validate       # usa Flyway para crear tablas, no hibernate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
        jdbc:
          '[time_zone]': UTC

  # === Mongo ===
  data:
    mongodb:
      uri: mongodb://localhost:27017/accounts_qry
      database: accounts_qry

  # Asegura ISO8601 y no timestamps en application.yml:
  jackson:
    serialization:
      write-dates-as-timestamps: false

  # === DATASOURCE: conexión a PostgreSQL ===
  datasource:
    url: jdbc:postgresql://localhost:5432/accounts_cmd
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:root}
    hikari:
      maximum-pool-size: 10

  # === FLYWAY: migraciones automáticas ===
  flyway:
    enabled: true
    validate-migration-naming: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  # === RABBITMQ: sistema de mensajería ===
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}

# === LOGGING ===
logging:
  level:
    root: INFO
    com:
      agromercado:
        accounts: DEBUG

# === ACTUATOR: endpoints de monitoreo ===
management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  jwt:
    dev:
      enabled: true
      secret: dev-0123456789abcdef-0123456789abcd
      ttl-seconds: 3600

# === Eureka Client Configuration ===
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}