server:
  port: 8761  # Puerto estándar de Eureka

spring:
  application:
    name: eureka-server
  # Deshabilita JMX completamente
  jmx:
    enabled: false

eureka:
  instance:
    hostname: localhost
  client:
    # Este servidor NO debe registrarse a sí mismo
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # Deshabilita la auto-preservación en desarrollo para que elimine servicios caídos rápidamente
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000

# Logging
logging:
  level:
    '[com.netflix.eureka]': INFO
    '[com.netflix.discovery]': INFO
    # Oculta los errores de JMX
    '[com.netflix.eureka.resources]': WARN

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info
    # Deshabilita completamente JMX en Actuator
    jmx:
      exposure:
        exclude: "*"
  endpoint:
    health:
      show-details: always
