server:
  port: 8081  # Puerto de ejecución del microservicio

spring:
  application:
    name: accounts-service  # Nombre de la app (aparece en logs y actuator)

  # === DATASOURCE: conexión a PostgreSQL ===
  datasource:
    url: jdbc:postgresql://localhost:5432/accounts_cmd
    username: ${POSTGRES_USER:accounts}
    password: ${POSTGRES_PASSWORD:accounts}
    hikari:
      maximum-pool-size: 10

  # === JPA / HIBERNATE ===
  jpa:
    hibernate:
      ddl-auto: validate       # usa Flyway para crear tablas, no hibernate
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC

  # === FLYWAY: migraciones automáticas ===
  flyway:
    enabled: true
    validate-migration-naming: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  # === RABBITMQ: sistema de mensajería ===
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}

# === LOGGING ===
logging:
  level:
    root: INFO
    com.agromercado.accounts: DEBUG

# === ACTUATOR: endpoints de monitoreo ===
management:
  endpoints:
    web:
      exposure:
        include: health,info



jackson:
  serialization:
    write-dates-as-timestamps: false